micronaut:
  application:
    name: cdcConsumer
  executors:
    fetcher:
      type: FIXED
      number-of-threads: 4
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: false
  server:
    port: 8081
    enabled: false
  caches:
    elasticache:
      maximum-size: 10

endpoints:
  all:
    port: 8085
  info:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
  stop:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
    binders:
      jvm:
        enabled: true
      web:
        enabled: true
      uptime:
        enabled: true
      processor:
        enabled: true
  prometheus:
    enabled: true
    sensitive: false
  health:
    cassandra:
      enabled: true
    elasticsearch:
      rest:
        high:
          level:
            enabled: false
---
pulsar:
  serviceUrl: "pulsar://localhost:6650"
  topic: "persistent://public/default/topic1"
  subscription: "sub1"
---
cassandra:
  default:
    basic:
      contact-points:
        - "127.0.0.1:9042"
      load-balancing-policy:
        local-datacenter: DC1
    advanced:
      control-connection:
        schema-agreement:
          timeout: 30
      metadata:
        schema:
          enabled: true
---
elasticsearch:
  httpHosts: "http://localhost:9200"
