apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra-stress
spec:
  serviceName: "cassandra-stress"
  replicas: 2
  selector:
    matchLabels:
      app: cassandra-stress
  template:
    metadata:
      labels:
        app: cassandra-stress
        cassandra.datastax.com/cluster: cluster2
        cassandra.datastax.com/datacenter: dc1
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
    spec:
      containers:
        - name: cassandra-stress
          image: vroyer/cassandra-stress:latest
          command: [ "/opt/dse/resources/cassandra/tools/bin/cassandra-stress", "user", "profile=/table1.yaml", "no-warmup", "ops(insert=1)", "n=90000000000", "-rate", "threads=1", "-node", "{{CASSANDRA_SERVICE}}", "-jmx", "-mode", "native", "cql3", "user={{CASSANDRA_USERNAME}}", "password={{CASSANDRA_PASSWORD}}" ]
          ports:
            - containerPort: 8081
              name: prometheus
          env:
            - name: JVM_OPTS
              value: -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=5001 -Dcom.sun.management.jmxremote.port=5001 -javaagent:/jmx_prometheus_javaagent-0.16.1.jar=8081:/jmx_exporter_config.yaml
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
