apiVersion: v1
kind: Service
metadata:
  labels:
    app: quasar
  name: quasar
spec:
  clusterIP: None
  ports:
    - port: 8081
  selector:
    app: quasar
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quasar
  labels:
    app: quasar
spec:
  serviceName: quasar
  replicas: 3
  selector:
    matchLabels:
      app: quasar
  template:
    metadata:
      labels:
        app: quasar
    spec:
      terminationGracePeriodSeconds: 300
      imagePullSecrets:
        - name: regcred
      containers:
        - name: quasar
          image: "vrtestregistry.azurecr.io/datastax/cassandra-cdc-quasar-consumer:0.1-SNAPSHOT"
          imagePullPolicy: Always
          terminationMessagePolicy: "FallbackToLogsOnError"
          env:
            - name: SERVER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: QUASAR_SERVICE_NAME
              value: "quasar"
            - name: QUASAR_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"
          ports:
            - containerPort: 8081
              name: http
            - containerPort: 8085
              name: endpoint
          livenessProbe:
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8081
            initialDelaySeconds: 15
            timeoutSeconds: 5