micronaut:
  application:
    name: cdcProducer
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: false
  server:
    port: "${SERVER_PORT:8082}"
    host: "${SERVER_HOST:`localhost`}"
endpoints:
  all:
    port: "${ENDPOINTS_PORT:8086}"
    host: "${ENDPOINTS_HOST:`localhost`}"
  info:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
  stop:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
    binders:
      jvm:
        enabled: true
      web:
        enabled: true
      uptime:
        enabled: true
      processor:
        enabled: true
  prometheus:
    enabled: true
    sensitive: false
---
pulsar:
  serviceUrl: "${PULSAR_SERVICE_URL:`pulsar://localhost:6650`}"
  topicPrefix: "${PULSAR_TOPIC_PREFIX:`persistent://public/default/dirty`}"
---
cassandra-cdc:
  clusterName: Test cluster
  nodeId: 263a0473-6297-4c99-b70a-3b0632cfc03a
  cassandraStorageDir: "${CASSANDRA_DATA:`/Users/vroyer/git/apache/cassandra/data`}"
  cassandraConfDir: "${CASSANDRA_CONF:`/Users/vroyer/git/apache/cassandra/conf`}"
  cassandraConfigFile: "${CASSANDRA_CONFIG:`cassandra.yaml`}"
  cassandraSnitchFile: "${CASSANDRA_SNITCH:`cassandra-rackdc.properties`}"
  commitLogRelocationDir: cdc
  offsetBackingStoreDir: cdc
  errorCommitLogReprocessEnabled: false
  latestCommitLogOnly: false
  tombstonesOnDelete: true
  fetchRow: false
---
