micronaut:
  application:
    name: cdcProducer
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: false
  server:
    port: "${SERVER_PORT:8082}"
    host: "${SERVER_HOST:`localhost`}"

endpoints:
  all:
    port: "${ENDPOINTS_PORT:8086}"
    host: "${SERVER_HOST:`localhost`}"
  info:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
  stop:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
    binders:
      jvm:
        enabled: true
      web:
        enabled: true
      uptime:
        enabled: true
      processor:
        enabled: true
  prometheus:
    enabled: true
    sensitive: false
---
pulsar:
  serviceUrl: "${PULSAR_SERVICE_URL:`pulsar://localhost:6650`}"
  topic: "${PULSAR_TOPIC:`persistent://public/default/topic1`}"
#quasarcli:
#  dnsNamePrefix: "${QUASAR_DNS_NAME_PREFIX:`quasar-`}"
---
cassandra-cdc:
  clusterName: Test cluster
  nodeId: 263a0473-6297-4c99-b70a-3b0632cfc03a
  cassandraStorageDir: "${CASSANDRA_DATA:`/var/lib/cassandra`}"
  cassandraConfDir: "${CASSANDRA_CONF:`/etc/cassandra`}"
  cassandraConfigFile: "${CASSANDRA_CONFIG:`cassandra.yaml`}"
  cassandraSnitchFile: "${CASSANDRA_SNITCH:`cassandra-rackdc.properties`}"
  commitLogRelocationDir: cdc
  offsetBackingStoreDir: cdc
  errorCommitLogReprocessEnabled: false
  latestCommitLogOnly: false
  tombstonesOnDelete: true
  fetchRow: false
---
#cassandra:
#  default:
#    basic:
#      contact-points:
#        - "${CASSANDRA_CONTACTPOINT:`localhost:9042`}"
#      load-balancing-policy:
#        local-datacenter: "${CASSANDRA_DATACENTER:`DC1`}"
#    advanced:
#      control-connection:
#        schema-agreement:
#          timeout: 30
#      metadata:
#        schema:
#          enabled: true
