name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PULSAR_IMAGE: strapdata/pulsar-all:latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Get project version
        uses: HardNorth/github-version-generate@v1.1.1
        with:
          version-source: file
          version-file: gradle.properties
          version-file-extraction-pattern: '(?<=version=).+'

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Test with Gradle
        run: ./gradlew test -PpulsarVersion=2.8.1 -x :producer-dse4:test -x :producer-dse4-pulsar:test

      - name: Build with Gradle
        run: ./gradlew assemble -PpulsarVersion=2.8.1 -x producer-dse4:assemble -x producer-dse4-pulsar:assemble

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Release Tar
        id: upload-release-tar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: distribution/build/distributions/cassandra-source-connectors-${{ env.RELEASE_VERSION }}.tar
          asset_name: cassandra-source-connectors-${{ env.RELEASE_VERSION }}.tar
          asset_content_type: application/tar
      - name: Upload Release Zip
        id: upload-release-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: distribution/build/distributions/cassandra-source-connectors-${{ env.RELEASE_VERSION }}.zip
          asset_name: cassandra-source-connectors-${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip
